# Número de réplicas
replicaCount: 1

# Imagen del contenedor
image:
  repository: ghcr.io/example/pythonapp
  tag: latest
  pullPolicy: IfNotPresent

# Configuración del servicio
service:
  type: ClusterIP
  nodePort: 30080

# Recursos
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Ingress
ingress:
  enabled: false
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: Prefix

# Autoescalado
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
