# Número de réplicas
replicaCount: 1

# Imagen del contenedor
image:
  repository: ghcr.io/example/pythonapp
  tag: latest
  pullPolicy: IfNotPresent

# Configuración del servicio
service:
  type: ClusterIP   # opciones: ClusterIP, NodePort, LoadBalancer
  nodePort: 30080   # solo aplica si service.type = NodePort

# Recursos
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Ingress
ingress:
  enabled: false
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: Prefix
